weather.api.url=${URL}
weather.api.key=${API_KEY}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

server.port=8082

smartlife.events.exchange=eventos
smartlife.events.routing-keys.venta-registrada=venta.registrada
